apiVersion: v1
kind: Service
metadata:
  labels:
    app: crud-shopping
  name: crud-shopping
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: crud-shopping
  type: ClusterIP
