apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/postgres-configmap.yml
  - postgres/postgres-statefulset.yml
  - postgres/postgres-services.yml
  - crud-shopping-configmap.yml
  - crud-shopping-deployment.yml
  - crud-shopping-services.yml




